#!/usr/bin/env bash
gcc -Wall -Wextra -Werror -pedantic  -std=gnu89 0-bubble_sort.c 0-main.c print_array.c -o bubble
echo "starting bubble"
./bubble
rm ./bubble
echo "ending bubble"

gcc -Wall -Wextra -Werror -pedantic  -std=gnu89 1-main.c 1-insertion_sort_list.c print_list.c -o insertion
echo "starting insertion"
./insertion
rm insertion
echo "ending insertion"

gcc -Wall -Wextra -Werror -pedantic  -std=gnu89 2-main.c 2-selection_sort.c print_array.c -o select
echo "starting select"
./select
echo "ending select"
rm ./select

gcc -Wall -Wextra -Werror -pedantic  -std=gnu89 3-main.c 3-quick_sort.c print_array.c -o quick
echo " Starting quick"
./quick
echo "ending quick"
rm ./quick
